[package]
name = "elrond-ico-sc"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "Ice <icegriffin1122@gmail.com>",]

[lib]
path = "src/ico_manager.rs"

[dependencies.elrond-wasm]
version = "0.27.4"

[dev-dependencies.elrond-wasm-debug]
version = "0.27.4"
